cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED XRAY_HEADER OR NOT XRAY_HEADER)
  message(FATAL_ERROR "XRAY_HEADER is required.")
endif()

if(NOT EXISTS "${XRAY_HEADER}")
  message(FATAL_ERROR "XRAY_HEADER does not exist: ${XRAY_HEADER}")
endif()

file(READ "${XRAY_HEADER}" header_text)
string(REPLACE "\r\n" "\n" header_text "${header_text}")
string(REPLACE "\r" "\n" header_text "${header_text}")
# C prototypes end with semicolons, so escape them before using a CMake list
# as the line container.
string(REPLACE ";" "\\;" header_text "${header_text}")
string(REPLACE "\n" ";" header_lines "${header_text}")

set(api_count 0)
set(missing_docs "")
set(index 0)

foreach(line IN LISTS header_lines)
  if(line MATCHES "^XRAY_API[ \t].*\\(")
    math(EXPR api_count "${api_count} + 1")
    math(EXPR line_number "${index} + 1")

    math(EXPR doc_end_index "${index} - 1")
    set(doc_end "")
    while(doc_end_index GREATER -1)
      list(GET header_lines ${doc_end_index} previous_line)
      string(STRIP "${previous_line}" previous_trimmed)
      if(NOT previous_trimmed STREQUAL "")
        set(doc_end "${previous_trimmed}")
        break()
      endif()
      math(EXPR doc_end_index "${doc_end_index} - 1")
    endwhile()

    set(has_doxygen_block OFF)
    if(doc_end STREQUAL "*/")
      set(scan_index ${doc_end_index})
      while(scan_index GREATER -1)
        list(GET header_lines ${scan_index} doc_line)
        string(STRIP "${doc_line}" doc_trimmed)
        if(doc_trimmed STREQUAL "/**")
          set(has_doxygen_block ON)
          break()
        endif()
        if(doc_trimmed MATCHES "^XRAY_API[ \t]")
          break()
        endif()
        math(EXPR scan_index "${scan_index} - 1")
      endwhile()
    endif()

    if(NOT has_doxygen_block)
      string(STRIP "${line}" declaration)
      list(APPEND missing_docs "${line_number}: ${declaration}")
    endif()
  endif()
  math(EXPR index "${index} + 1")
endforeach()

if(api_count EQUAL 0)
  message(FATAL_ERROR "No XRAY_API declarations found in ${XRAY_HEADER}.")
endif()

list(LENGTH missing_docs missing_count)
if(missing_count GREATER 0)
  string(JOIN "\n  " missing_text ${missing_docs})
  message(FATAL_ERROR "Missing Doxygen documentation for ${missing_count} exported function(s):\n  ${missing_text}")
endif()

message(STATUS "Documented XRAY_API declarations: ${api_count}/${api_count}")
