cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED XRAY_HEADER OR NOT XRAY_HEADER)
  message(FATAL_ERROR "XRAY_HEADER is required.")
endif()

if(NOT DEFINED XRAY_OUTPUT OR NOT XRAY_OUTPUT)
  message(FATAL_ERROR "XRAY_OUTPUT is required.")
endif()

if(NOT EXISTS "${XRAY_HEADER}")
  message(FATAL_ERROR "XRAY_HEADER does not exist: ${XRAY_HEADER}")
endif()

function(xray_json_escape output input)
  set(value "${input}")
  string(REPLACE "\\" "\\\\" value "${value}")
  string(REPLACE "\"" "\\\"" value "${value}")
  string(REPLACE "\n" "\\n" value "${value}")
  set(${output} "${value}" PARENT_SCOPE)
endfunction()

function(xray_clean_doc_line output input)
  string(STRIP "${input}" value)
  string(REGEX REPLACE "^\\*[ \t]?" "" value "${value}")
  set(${output} "${value}" PARENT_SCOPE)
endfunction()

function(xray_api_parameters_json output signature)
  string(REGEX REPLACE "^.*\\(" "" parameter_text "${signature}")
  string(REGEX REPLACE "\\)[ \t]*;?$" "" parameter_text "${parameter_text}")
  string(STRIP "${parameter_text}" parameter_text)

  if(parameter_text STREQUAL "" OR parameter_text STREQUAL "void")
    set(${output} "[]" PARENT_SCOPE)
    return()
  endif()

  string(REPLACE "," ";" parameter_list "${parameter_text}")
  set(parameter_json "[")
  set(parameter_count 0)
  foreach(parameter IN LISTS parameter_list)
    string(STRIP "${parameter}" parameter)
    string(REGEX REPLACE "[ \t]+" " " parameter "${parameter}")
    string(REGEX REPLACE ".*[ \t\\*]([A-Za-z_][A-Za-z0-9_]*)$" "\\1" parameter_name "${parameter}")
    if(parameter_name STREQUAL parameter)
      message(FATAL_ERROR "Could not parse parameter name from: ${parameter}")
    endif()
    string(FIND "${parameter}" "${parameter_name}" parameter_name_index)
    if(parameter_name_index LESS 1)
      message(FATAL_ERROR "Could not parse parameter type from: ${parameter}")
    endif()
    string(SUBSTRING "${parameter}" 0 ${parameter_name_index} parameter_type)
    string(STRIP "${parameter_type}" parameter_type)
    xray_json_escape(parameter_type_json "${parameter_type}")

    if(parameter_count GREATER 0)
      string(APPEND parameter_json ", ")
    endif()
    string(APPEND parameter_json "{\"name\": \"${parameter_name}\", \"type\": \"${parameter_type_json}\"}")
    math(EXPR parameter_count "${parameter_count} + 1")
  endforeach()
  string(APPEND parameter_json "]")
  set(${output} "${parameter_json}" PARENT_SCOPE)
endfunction()

function(xray_api_parameters_markdown output signature)
  string(REGEX REPLACE "^.*\\(" "" parameter_text "${signature}")
  string(REGEX REPLACE "\\)[ \t]*;?$" "" parameter_text "${parameter_text}")
  string(STRIP "${parameter_text}" parameter_text)

  if(parameter_text STREQUAL "" OR parameter_text STREQUAL "void")
    set(${output} "None." PARENT_SCOPE)
    return()
  endif()

  string(REPLACE "," ";" parameter_list "${parameter_text}")
  set(parameter_markdown "| Name | Type |\n| --- | --- |")
  foreach(parameter IN LISTS parameter_list)
    string(STRIP "${parameter}" parameter)
    string(REGEX REPLACE "[ \t]+" " " parameter "${parameter}")
    string(REGEX REPLACE ".*[ \t\\*]([A-Za-z_][A-Za-z0-9_]*)$" "\\1" parameter_name "${parameter}")
    if(parameter_name STREQUAL parameter)
      message(FATAL_ERROR "Could not parse parameter name from: ${parameter}")
    endif()
    string(FIND "${parameter}" "${parameter_name}" parameter_name_index)
    if(parameter_name_index LESS 1)
      message(FATAL_ERROR "Could not parse parameter type from: ${parameter}")
    endif()
    string(SUBSTRING "${parameter}" 0 ${parameter_name_index} parameter_type)
    string(STRIP "${parameter_type}" parameter_type)
    string(APPEND parameter_markdown "\n| `${parameter_name}` | `${parameter_type}` |")
  endforeach()
  set(${output} "${parameter_markdown}" PARENT_SCOPE)
endfunction()

function(xray_api_category_title output category)
  if(category STREQUAL "scratch-bigint")
    set(title "Scratch BigInt")
  elseif(category STREQUAL "factoring")
    set(title "Factoring")
  elseif(category STREQUAL "cyclotomic")
    set(title "Cyclotomic")
  elseif(category STREQUAL "benchmark")
    set(title "Benchmark")
  elseif(category STREQUAL "gnfs")
    set(title "GNFS")
  elseif(category STREQUAL "workbench")
    set(title "Workbench")
  elseif(category STREQUAL "cpu")
    set(title "CPU")
  elseif(category STREQUAL "expression")
    set(title "Expression")
  elseif(category STREQUAL "runtime")
    set(title "Runtime")
  else()
    set(title "Utility")
  endif()
  set(${output} "${title}" PARENT_SCOPE)
endfunction()

function(xray_api_category output name)
  if(name MATCHES "^xray_bigint_")
    set(category "scratch-bigint")
  elseif(name MATCHES "^xray_factor|^xray_is_probable_prime|^xray_integer_nth_root|^xray_small_factor|^xray_fermat_factor|^xray_pollard_|^xray_brent_|^xray_perfect_power")
    set(category "factoring")
  elseif(name MATCHES "^xray_cyclotomic|^xray_phi")
    set(category "cyclotomic")
  elseif(name MATCHES "^xray_benchmark|^xray_scratch_adoption")
    set(category "benchmark")
  elseif(name MATCHES "^xray_gnfs")
    set(category "gnfs")
  elseif(name MATCHES "^xray_workbench|^xray_run_")
    set(category "workbench")
  elseif(name MATCHES "^xray_cpu")
    set(category "cpu")
  elseif(name MATCHES "^xray_parse|^xray_evaluate|^xray_expression")
    set(category "expression")
  elseif(name MATCHES "^xray_version|^xray_abi|^xray_bignum|^xray_free")
    set(category "runtime")
  else()
    set(category "utility")
  endif()
  set(${output} "${category}" PARENT_SCOPE)
endfunction()

function(xray_api_ownership output name return_type)
  if(name MATCHES "_clear$")
    set(ownership "clears-caller-owned-struct")
  elseif(return_type STREQUAL "char *")
    set(ownership "caller-owned:xray_free")
  elseif(return_type STREQUAL "const char *")
    set(ownership "borrowed")
  elseif(return_type STREQUAL "void")
    set(ownership "none")
  elseif(return_type MATCHES "^Xray.*Config$")
    set(ownership "value")
  else()
    set(ownership "value-or-status")
  endif()
  set(${output} "${ownership}" PARENT_SCOPE)
endfunction()

get_filename_component(header_name "${XRAY_HEADER}" NAME)
file(READ "${XRAY_HEADER}" header_text)
string(REPLACE "\r\n" "\n" header_text "${header_text}")
string(REPLACE "\r" "\n" header_text "${header_text}")
string(REPLACE ";" "\\;" header_text "${header_text}")
string(REPLACE "\n" ";" header_lines "${header_text}")

set(api_count 0)
set(json "{\n")
string(APPEND json "  \"schemaVersion\": 2,\n")
string(APPEND json "  \"generatedFrom\": \"${header_name}\",\n")
string(APPEND json "  \"docSource\": \"${header_name}\",\n")
string(APPEND json "  \"functions\": [\n")

set(markdown_enabled OFF)
if(DEFINED XRAY_MARKDOWN_OUTPUT AND NOT XRAY_MARKDOWN_OUTPUT STREQUAL "")
  set(markdown_enabled ON)
  set(markdown "# Number X-Ray C API Reference\n\n")
  string(APPEND markdown "Generated from `${header_name}`. This file is produced at configure time from the same documented `XRAY_API` declarations as `number-xray-api.json`.\n\n")
endif()

set(in_doc OFF)
set(current_doc "")
set(current_summary "")
set(pending_doc "")
set(pending_summary "")
set(last_markdown_category "")

foreach(line IN LISTS header_lines)
  string(STRIP "${line}" declaration)
  if(declaration STREQUAL "/**")
    set(in_doc ON)
    set(current_doc "")
    set(current_summary "")
  elseif(in_doc)
    if(declaration STREQUAL "*/")
      set(in_doc OFF)
      set(pending_doc "${current_doc}")
      set(pending_summary "${current_summary}")
    else()
      xray_clean_doc_line(doc_line "${line}")
      if(NOT current_doc STREQUAL "")
        string(APPEND current_doc "\n")
      endif()
      string(APPEND current_doc "${doc_line}")
      string(STRIP "${doc_line}" doc_line_trimmed)
      if(current_summary STREQUAL "" AND NOT doc_line_trimmed STREQUAL "")
        set(current_summary "${doc_line_trimmed}")
      endif()
    endif()
  endif()

  if(declaration MATCHES "^XRAY_API[ \t].*\\(")
    if(pending_summary STREQUAL "" OR pending_doc STREQUAL "")
      message(FATAL_ERROR "Missing Doxygen documentation before XRAY_API declaration: ${declaration}")
    endif()

    string(REGEX REPLACE "^XRAY_API[ \t]+" "" signature "${declaration}")
    string(REGEX REPLACE "\\(.*$" "" prefix "${signature}")
    string(REGEX REPLACE ".*[ \t\\*]([A-Za-z_][A-Za-z0-9_]*)$" "\\1" name "${prefix}")
    if(name STREQUAL prefix)
      message(FATAL_ERROR "Could not parse XRAY_API function name from: ${declaration}")
    endif()

    string(FIND "${signature}" "${name}" name_index)
    if(name_index LESS 1)
      message(FATAL_ERROR "Could not parse XRAY_API return type from: ${declaration}")
    endif()
    string(SUBSTRING "${signature}" 0 ${name_index} return_type)
    string(STRIP "${return_type}" return_type)

    xray_api_category(category "${name}")
    xray_api_ownership(ownership "${name}" "${return_type}")
    xray_api_parameters_json(parameters_json "${signature}")
    xray_api_parameters_markdown(parameters_markdown "${signature}")
    xray_json_escape(declaration_json "${declaration}")
    xray_json_escape(return_type_json "${return_type}")
    xray_json_escape(summary_json "${pending_summary}")
    xray_json_escape(documentation_json "${pending_doc}")

    if(markdown_enabled)
      if(NOT category STREQUAL last_markdown_category)
        xray_api_category_title(category_title "${category}")
        string(APPEND markdown "\n## ${category_title}\n\n")
        set(last_markdown_category "${category}")
      endif()
      string(APPEND markdown "### `${name}`\n\n")
      string(APPEND markdown "```c\n${declaration}\n```\n\n")
      string(APPEND markdown "- Category: `${category}`\n")
      string(APPEND markdown "- Return type: `${return_type}`\n")
      string(APPEND markdown "- Ownership: `${ownership}`\n\n")
      string(APPEND markdown "**Parameters**\n\n${parameters_markdown}\n\n")
      string(APPEND markdown "**Documentation**\n\n${pending_doc}\n\n")
    endif()

    if(api_count GREATER 0)
      string(APPEND json ",\n")
    endif()
    string(APPEND json "    {")
    string(APPEND json "\"name\": \"${name}\", ")
    string(APPEND json "\"category\": \"${category}\", ")
    string(APPEND json "\"returnType\": \"${return_type_json}\", ")
    string(APPEND json "\"ownership\": \"${ownership}\", ")
    string(APPEND json "\"summary\": \"${summary_json}\", ")
    string(APPEND json "\"documentation\": \"${documentation_json}\", ")
    string(APPEND json "\"parameters\": ${parameters_json}, ")
    string(APPEND json "\"declaration\": \"${declaration_json}\"")
    string(APPEND json "}")

    set(pending_doc "")
    set(pending_summary "")
    math(EXPR api_count "${api_count} + 1")
  endif()
endforeach()

if(api_count EQUAL 0)
  message(FATAL_ERROR "No XRAY_API declarations found in ${XRAY_HEADER}.")
endif()

string(APPEND json "\n  ],\n")
string(APPEND json "  \"functionCount\": ${api_count}\n")
string(APPEND json "}\n")

file(WRITE "${XRAY_OUTPUT}" "${json}")
if(markdown_enabled)
  string(APPEND markdown "\nFunction count: ${api_count}\n")
  file(WRITE "${XRAY_MARKDOWN_OUTPUT}" "${markdown}")
endif()
message(STATUS "Generated Number X-Ray API catalog with ${api_count} functions: ${XRAY_OUTPUT}")
if(markdown_enabled)
  message(STATUS "Generated Number X-Ray API reference: ${XRAY_MARKDOWN_OUTPUT}")
endif()
