cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED XRAY_HEADER OR NOT XRAY_HEADER)
  message(FATAL_ERROR "XRAY_HEADER is required.")
endif()

if(NOT DEFINED XRAY_OUTPUT OR NOT XRAY_OUTPUT)
  message(FATAL_ERROR "XRAY_OUTPUT is required.")
endif()

if(NOT EXISTS "${XRAY_HEADER}")
  message(FATAL_ERROR "XRAY_HEADER does not exist: ${XRAY_HEADER}")
endif()

function(xray_json_escape output input)
  set(value "${input}")
  string(REPLACE "\\" "\\\\" value "${value}")
  string(REPLACE "\"" "\\\"" value "${value}")
  set(${output} "${value}" PARENT_SCOPE)
endfunction()

function(xray_api_category output name)
  if(name MATCHES "^xray_bigint_")
    set(category "scratch-bigint")
  elseif(name MATCHES "^xray_factor|^xray_is_probable_prime|^xray_integer_nth_root|^xray_small_factor|^xray_fermat_factor|^xray_pollard_|^xray_brent_|^xray_perfect_power")
    set(category "factoring")
  elseif(name MATCHES "^xray_cyclotomic|^xray_phi")
    set(category "cyclotomic")
  elseif(name MATCHES "^xray_benchmark|^xray_scratch_adoption")
    set(category "benchmark")
  elseif(name MATCHES "^xray_gnfs")
    set(category "gnfs")
  elseif(name MATCHES "^xray_workbench|^xray_run_")
    set(category "workbench")
  elseif(name MATCHES "^xray_cpu")
    set(category "cpu")
  elseif(name MATCHES "^xray_parse|^xray_evaluate|^xray_expression")
    set(category "expression")
  elseif(name MATCHES "^xray_version|^xray_abi|^xray_bignum|^xray_free")
    set(category "runtime")
  else()
    set(category "utility")
  endif()
  set(${output} "${category}" PARENT_SCOPE)
endfunction()

function(xray_api_ownership output name return_type)
  if(name MATCHES "_clear$")
    set(ownership "clears-caller-owned-struct")
  elseif(return_type STREQUAL "char *")
    set(ownership "caller-owned:xray_free")
  elseif(return_type STREQUAL "const char *")
    set(ownership "borrowed")
  elseif(return_type STREQUAL "void")
    set(ownership "none")
  elseif(return_type MATCHES "^Xray.*Config$")
    set(ownership "value")
  else()
    set(ownership "value-or-status")
  endif()
  set(${output} "${ownership}" PARENT_SCOPE)
endfunction()

get_filename_component(header_name "${XRAY_HEADER}" NAME)
file(READ "${XRAY_HEADER}" header_text)
string(REPLACE "\r\n" "\n" header_text "${header_text}")
string(REPLACE "\r" "\n" header_text "${header_text}")
string(REPLACE ";" "\\;" header_text "${header_text}")
string(REPLACE "\n" ";" header_lines "${header_text}")

set(api_count 0)
set(json "{\n")
string(APPEND json "  \"schemaVersion\": 1,\n")
string(APPEND json "  \"generatedFrom\": \"${header_name}\",\n")
string(APPEND json "  \"docSource\": \"${header_name}\",\n")
string(APPEND json "  \"functions\": [\n")

foreach(line IN LISTS header_lines)
  string(STRIP "${line}" declaration)
  if(declaration MATCHES "^XRAY_API[ \t].*\\(")
    string(REGEX REPLACE "^XRAY_API[ \t]+" "" signature "${declaration}")
    string(REGEX REPLACE "\\(.*$" "" prefix "${signature}")
    string(REGEX REPLACE ".*[ \t\\*]([A-Za-z_][A-Za-z0-9_]*)$" "\\1" name "${prefix}")
    if(name STREQUAL prefix)
      message(FATAL_ERROR "Could not parse XRAY_API function name from: ${declaration}")
    endif()

    string(FIND "${signature}" "${name}" name_index)
    if(name_index LESS 1)
      message(FATAL_ERROR "Could not parse XRAY_API return type from: ${declaration}")
    endif()
    string(SUBSTRING "${signature}" 0 ${name_index} return_type)
    string(STRIP "${return_type}" return_type)

    xray_api_category(category "${name}")
    xray_api_ownership(ownership "${name}" "${return_type}")
    xray_json_escape(declaration_json "${declaration}")
    xray_json_escape(return_type_json "${return_type}")

    if(api_count GREATER 0)
      string(APPEND json ",\n")
    endif()
    string(APPEND json "    {")
    string(APPEND json "\"name\": \"${name}\", ")
    string(APPEND json "\"category\": \"${category}\", ")
    string(APPEND json "\"returnType\": \"${return_type_json}\", ")
    string(APPEND json "\"ownership\": \"${ownership}\", ")
    string(APPEND json "\"declaration\": \"${declaration_json}\"")
    string(APPEND json "}")

    math(EXPR api_count "${api_count} + 1")
  endif()
endforeach()

if(api_count EQUAL 0)
  message(FATAL_ERROR "No XRAY_API declarations found in ${XRAY_HEADER}.")
endif()

string(APPEND json "\n  ],\n")
string(APPEND json "  \"functionCount\": ${api_count}\n")
string(APPEND json "}\n")

file(WRITE "${XRAY_OUTPUT}" "${json}")
message(STATUS "Generated Number X-Ray API catalog with ${api_count} functions: ${XRAY_OUTPUT}")
